/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formlar;

/**
 *
 * @author rbarka
 */
public class frmKanGrubu extends javax.swing.JFrame {

    /**
     * Creates new form frmKanGrubu
     */
    public frmKanGrubu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkangrubu = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnyenikaydet = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnsorgula = new javax.swing.JButton();
        btnduzenle = new javax.swing.JButton();
        btnsil = new javax.swing.JButton();
        btncikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtkangrubu);
        txtkangrubu.setBounds(80, 40, 130, 20);
        getContentPane().add(txtid);
        txtid.setBounds(80, 10, 130, 20);

        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 50, 14);

        jLabel3.setText("Kan Grubu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 60, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Kan Grubu"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 520, 220);

        btnyenikaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yeni_kayit.png"))); // NOI18N
        btnyenikaydet.setText("Yeni Kayıt");
        btnyenikaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnyenikaydet);
        btnyenikaydet.setBounds(10, 300, 107, 33);

        btnkaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/duzenle.png"))); // NOI18N
        btnkaydet.setText("Kaydet");
        btnkaydet.setMaximumSize(new java.awt.Dimension(107, 33));
        btnkaydet.setMinimumSize(new java.awt.Dimension(107, 33));
        btnkaydet.setPreferredSize(new java.awt.Dimension(107, 33));
        getContentPane().add(btnkaydet);
        btnkaydet.setBounds(120, 300, 107, 33);

        btnsorgula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorgula.png"))); // NOI18N
        btnsorgula.setText("Sorgula");
        btnsorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsorgula);
        btnsorgula.setBounds(230, 300, 97, 33);

        btnduzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/duzenle.png"))); // NOI18N
        btnduzenle.setText("Düzenle");
        getContentPane().add(btnduzenle);
        btnduzenle.setBounds(330, 300, 99, 33);

        btnsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sil.png"))); // NOI18N
        btnsil.setText("Sil");
        btnsil.setMaximumSize(new java.awt.Dimension(107, 33));
        btnsil.setMinimumSize(new java.awt.Dimension(107, 33));
        btnsil.setName(""); // NOI18N
        btnsil.setPreferredSize(new java.awt.Dimension(107, 33));
        getContentPane().add(btnsil);
        btnsil.setBounds(430, 300, 100, 33);

        btncikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cikis.png"))); // NOI18N
        btncikis.setText("Çıkış");
        getContentPane().add(btncikis);
        btncikis.setBounds(430, 340, 100, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/healthcare.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -2, 540, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnyenikaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikaydetActionPerformed

    }//GEN-LAST:event_btnyenikaydetActionPerformed

    private void btnsorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsorgulaActionPerformed

    }//GEN-LAST:event_btnsorgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKanGrubu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKanGrubu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKanGrubu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKanGrubu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKanGrubu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncikis;
    private javax.swing.JButton btnduzenle;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton btnsorgula;
    private javax.swing.JButton btnyenikaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkangrubu;
    // End of variables declaration//GEN-END:variables
}
